modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "createcobblestone"
version = "${version}"
displayName = "Create cobblestone"
authors = "MrStickyPiston"
description = '''
Adds a block generating cobblestone using SU, stopping cobblestone generators from eating your frames.
'''
logoFile = "icon.png"

[[dependencies.createcobblestone]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createcobblestone]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createcobblestone]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"